version: "3"
services:
  selenium:
    image: selenium/standalone-chromium:latest
    container_name: selenium
    ports:
      - "4444:4444"

  javaapp:
    build: .
    container_name: javaapp
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium
      - SELENIUM_URL=http://selenium:4444
