version: "3"
services:
  selenium:
    image: selenium/standalone-chromium:latest
    container_name: selenium
    ports:
      - "4444:4444"   # Selenium WebDriver

  javaapp:
    build: .
    container_name: javaapp
    depends_on:
      - selenium
